const deepThoughts = [
  "Before you judge React's virtual DOM, walk a mile in its shoes. Then, if you still don't like it, at least you're a mile away and you have its shoes.",
  "They say TypeScript is just JavaScript with a safety helmet. But remember, even with a helmet, you can still ride your bike into a wall of undefined behavior.",
  "CSS is like a box of chocolates. You think you know what you're getting, but then it turns out the box itself is actually a flex container with overflow: hidden.",
  "I once spent six hours debugging my Next.js app only to realize the error was between the keyboard and the chair. The chair was mine. I was the error.",
  "People say Node.js is non-blocking, but I've found it blocks me from having meaningful relationships with anyone who doesn't know what a callback is.",
  "Maybe the real responsive design was the friends we made along the viewport.",
  "They told me to think outside the box. So I used position: absolute and now everything is broken.",
  "Sometimes I stay awake at night wondering if I'm manipulating the DOM, or if the DOM is manipulating me.",
  "The useEffect cleanup function is a lot like saying goodbye to a friend at the airport. You know you need to do it, but most people just drive away.",
  "Before you marry someone, make them use Internet Explorer. That way you'll know what they're like when things don't work the way they're supposed to.",
  "If a tree falls in the forest and no one is around to hear it, does it make a sound? Similarly, if a website has perfect performance but no users, does it make a difference?",
  "They say you should comment your code as if the next developer who reads it is a violent psychopath who knows where you live. I am that next developer. I am also that psychopath.",
  "Remember, we're not 'reinventing the wheel' with each new JavaScript framework. We're just adding more wheels to a car that was already driving just fine.",
  "Someday, browsers will interpret our CSS exactly as we intended. And on that day, we'll all be unemployed.",
  "The journey of a thousand miles begins with a single step. The journey of a web developer begins with 'npm install' and ends with 'cannot find module'.",
  "I used to think the world was cruel and unfair. Then I tried to vertically center a div.",
  "I once had a dream where all my HTML was semantic and my JavaScript was concise. Then I woke up and realized I was holding my rubber duck.",
  "Maybe the real hoisting was the variables we declared along the way.",
  "They say if you love something, set it free. If it comes back, it's yours. If it doesn't, it was probably lost in a garbage collection cycle.",
  "Before you criticize someone's code, walk a mile in their codebase. Then, when you do criticize their code, you'll be a mile deep in technical debt and they won't be able to hear you.",
  "In the beginning, there was the div. And the developer saw that the div was good. So the developer put a div inside that div. And then another div inside that div. And now we have React.",
  "Sometimes I think my code is like a fine wine - it gets better with age. Then I come back to it six months later and realize it's more like milk.",
  "The best error messages are like poetry: short, cryptic, and they make you question your entire existence.",
  "They say FastAPI is faster than Express. But no framework is faster than the speed at which a client can change their requirements.",
  "If debugging is the process of removing bugs, then programming must be the process of adding them. I'm an excellent programmer.",
];

export default deepThoughts;
